kind: Service
apiVersion: v1
metadata:
  name: decaf-metabolica-production
spec:
  selector:
    app: decaf-metabolica
    env: production
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: decaf-metabolica-staging
spec:
  selector:
    app: decaf-metabolica
    env: staging
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
